<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FluxoDeCaixa.Lancamentos.Api\FluxoDeCaixa.Lancamentos.Api.csproj" />
    <ProjectReference Include="..\..\src\FluxoDeCaixa.Consolidado.Api\FluxoDeCaixa.Consolidado.Api.csproj" />
    <ProjectReference Include="..\..\src\FluxoDeCaixa.Consolidado.Worker\FluxoDeCaixa.Consolidado.Worker.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.13.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
</Project>
